import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pages} from '../src/data/content.mjs';
import {href} from '../src/ui.mjs';
const base=process.env.TEST_URL||'http://localhost:4173';
await fs.mkdir('reports',{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'light',reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const report={checks:[],accessibility:[],responsive:[],errors};
const passed=s=>{report.checks.push(s);console.log('PASS: '+s);};
async function go(url){await page.goto(base+url,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);}
async function audit(name){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();report.accessibility.push({name,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});console.log('A11Y: '+name+' — '+result.violations.length+' violations');}
try{
 await go('/');assert.equal(await page.locator('html').getAttribute('lang'),'en');await page.screenshot({path:'reports/desktop-hero.png'});await audit('English homepage / light');
 await page.locator('[data-open="theme-dialog"]').click();await page.locator('[name="theme-mode"][value="dark"]').check();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.keyboard.press('Escape');await go('/pricing/');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');passed('Theme preference persists across pages');
 await page.locator('[data-open="theme-dialog"]').click();await page.locator('[name="theme-mode"][value="auto"]').check();await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('#custom-color').fill('#1133aa');assert.equal(await page.evaluate(()=>localStorage.getItem('subromart.preferences.v1')&&JSON.parse(localStorage.getItem('subromart.preferences.v1')).color),'#1133aa');await page.locator('#reset-preferences').click();await page.keyboard.press('Escape');passed('Device auto, custom skin and reset work');
 await go('/solutions/');await page.locator('[data-filter="education"]').click();assert.equal(await page.locator('.product-card:visible').count(),2);await page.locator('#catalogue-search').fill('nothingmatches987');assert.equal(await page.locator('.product-card:visible').count(),0);assert(await page.locator('#filter-empty').isVisible());await page.locator('[data-reset-filters]').click();assert.equal(await page.locator('.product-card:visible').count(),8);passed('Category and search filters combine and reset');
 for(const id of ['school-management','edtech','healthcare'])await page.locator(`[data-compare="${id}"]`).click();await page.locator('[data-compare="ecommerce"]').click();assert.equal(await page.locator('#compare-count').textContent(),'3');await page.locator('#compare-bar a').click();await expect(page.locator('.comparison-table thead th')).toHaveCount(4);await page.locator('.remove-compare[data-compare="edtech"]').click();await expect(page.locator('.comparison-table thead th')).toHaveCount(3);assert((new URL(page.url()).searchParams.get('items')||'').includes('school-management'));passed('Comparison persists, limits selection, removes items and updates shareable URL');
 await go('/search/?q=%E0%A6%B8%E0%A7%8D%E0%A6%95%E0%A7%81%E0%A6%B2');await page.locator('.search-result').first().waitFor();assert((await page.locator('.search-result').count())>0);await page.locator('#page-search').fill('<img src=x onerror=alert(1)>');await page.waitForTimeout(300);assert.equal(await page.locator('#page-results img').count(),0);passed('Bilingual full-content search and safe empty-result handling');
 await go('/solutions/healthcare/');await page.locator('[data-demo="health"]').click();await page.waitForFunction(()=>document.querySelector('#demo-content [data-dashboard="health"]'));await page.locator('[data-preview-device="mobile"]').click();assert.equal(await page.locator('.demo-viewport').getAttribute('data-preview-size'),'mobile');await page.locator('#demo-solution').selectOption('commerce');await page.waitForFunction(()=>document.querySelector('#demo-content [data-dashboard="commerce"]'));await audit('Interactive demo dialog');await page.keyboard.press('Escape');passed('Demo changes solution and device, and Escape closes it');
 await go('/contact/?interest=healthcare');assert.equal(await page.locator('[name="interest"]').inputValue(),'healthcare');await page.locator('#prepare-brief').click();assert(await page.locator('#brief-form').isVisible());await page.locator('[name="message"]').fill('We need a clinic scheduling and billing system.');await page.locator('[name="name"]').fill('Test Person');await page.locator('[name="email"]').fill('test@example.org');await page.locator('[name="consent"]').check();await page.locator('#prepare-brief').click();await page.locator('#brief-result').waitFor();assert((await page.locator('#brief-preview').textContent()).includes('Test Person'));assert((await page.locator('#brief-whatsapp').getAttribute('href')).startsWith('https://wa.me/8801521409155?text='));assert((await page.locator('#brief-email').getAttribute('href')).startsWith('mailto:subrotodas1714037@gmail.com?'));const downloadPromise=page.waitForEvent('download');await page.locator('#download-brief').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'subromart-project-brief.txt');await page.locator('#edit-brief').click();assert.equal(await page.locator('[name="name"]').inputValue(),'Test Person');passed('Contact validation, message review, WhatsApp/email URLs, download and edit');
 await go('/project-planner/');assert(await page.locator('[data-form-step="0"]').isVisible());assert(!(await page.locator('[data-form-step="1"]').isVisible()));await page.locator('[name="interest"]').selectOption('mobile-apps');await page.locator('[name="message"]').fill('We need a bilingual app for our learning platform.');await page.locator('#form-next').click();assert(await page.locator('[data-form-step="1"]').isVisible());await page.locator('[name="features"]').first().check();await page.locator('#form-next').click();await page.locator('[name="name"]').fill('Planner Test');await page.locator('[name="email"]').fill('planner@example.org');await page.locator('[name="consent"]').check();await page.locator('#prepare-brief').click();await page.locator('#brief-result').waitFor();assert((await page.locator('#brief-preview').textContent()).includes('Admin dashboard'));passed('Three-step planner validates and includes selected features');
 await go('/book-demo/');assert(await page.locator('[name="preferredDate"]').getAttribute('min'));passed('Demo request has a current minimum date and explicit confirmation wording');
 await go('/');const start=await page.locator('#whatsapp-button').boundingBox();await page.mouse.move(start.x+25,start.y+25);await page.mouse.down();await page.mouse.move(70,190,{steps:15});await page.mouse.up();const moved=await page.locator('#whatsapp-button').boundingBox();assert(moved.x<120&&moved.y<240);assert.equal(context.pages().length,1);await page.reload({waitUntil:'networkidle'});const restored=await page.locator('#whatsapp-button').boundingBox();assert(Math.abs(restored.x-moved.x)<3);await page.locator('#whatsapp-button').focus();await page.keyboard.press('Shift+ArrowRight');const keyed=await page.locator('#whatsapp-button').boundingBox();assert(keyed.x>restored.x);passed('WhatsApp drag does not open chat; position persists and supports keyboard movement');
 await page.locator('[data-open="theme-dialog"]').click();await page.locator('#reset-preferences').click();await page.keyboard.press('Escape');
 const routes=['/','/bn/','/solutions/','/contact/','/solutions/school-management/','/bn/project-planner/','/pricing/','/about/'];
 for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await go(route);const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));report.responsive.push({width,route,...dimensions});assert(dimensions.scroll<=dimensions.viewport+1,`Overflow at ${width} ${route}: ${dimensions.scroll}`);}}passed('No horizontal overflow across 8 page types at 320, 390, 768, 1024 and 1440px');
 await page.setViewportSize({width:768,height:1000});await go('/');await page.locator('.tablet-menu-toggle').click();assert(await page.locator('#menu-dialog').isVisible());await page.keyboard.press('Escape');passed('Tablet has an accessible menu between mobile and desktop breakpoints');
 await page.setViewportSize({width:1440,height:1000});await go('/');await page.locator('.founder-image img').scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.querySelector('.founder-image img');return i.complete&&i.naturalWidth>0;});await page.locator('.founder-strip').screenshot({path:'reports/founder-section.png'});await page.locator('.product-grid').first().scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.product-grid img')].every(i=>i.complete&&i.naturalWidth>0));await page.locator('.product-grid').first().screenshot({path:'reports/product-gallery.png'});passed('Local founder portrait and product preview assets render correctly');
 await page.setViewportSize({width:390,height:844});await go('/');await page.screenshot({path:'reports/mobile-hero.png'});await page.locator('.bottom-nav [data-open="menu-dialog"]').click();assert(await page.locator('#menu-dialog').isVisible());await audit('Mobile drawer');await page.screenshot({path:'reports/mobile-drawer.png'});await page.keyboard.press('Escape');assert(await page.locator('.bottom-nav [data-open="menu-dialog"]').evaluate(e=>e===document.activeElement));passed('Mobile bottom navigation, drawer and focus restoration');
 await go('/bn/contact/');await audit('Bengali contact form / mobile');await page.screenshot({path:'reports/mobile-contact.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await go('/bn/');await page.locator('[data-open="theme-dialog"]').click();await page.locator('[name="theme-mode"][value="dark"]').check();await page.keyboard.press('Escape');await audit('Bengali homepage / dark');await page.screenshot({path:'reports/dark-hero.png'});
 for(const language of ['bn','en'])for(const p of pages){const route=href(p.slug,language);const response=await context.request.get(base+route);assert.equal(response.status(),200,route);}passed('All 74 language routes serve HTTP 200');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const p=await nojs.newPage();await p.goto(base+'/');assert(await p.locator('h1').isVisible());assert(!(await p.locator('.bottom-nav [data-open]').isVisible()));await p.locator('.bottom-nav a[href="/solutions/"]').click();assert(await p.locator('.product-card').first().isVisible());await nojs.close();passed('Core content and navigation work without JavaScript');
 assert.equal(errors.length,0,errors.join('\n'));passed('No uncaught JavaScript errors');
}finally{await fs.writeFile('reports/browser-results.json',JSON.stringify(report,null,2));await browser.close();}
const violations=report.accessibility.flatMap(a=>a.violations.map(v=>({page:a.name,...v})));
if(violations.length){console.log(JSON.stringify(violations,null,2));process.exitCode=1;}else console.log('PASS: No automated WCAG A/AA violations in audited views.');
