import { bi } from './data/content.mjs';
import { profile, tr, href, icon, button, ctaBlock } from './ui.mjs';

export function aboutPage(lang){const t=v=>tr(v,lang);return `<section class="container about-hero about-concise"><div><p class="eyebrow">SUBROMART</p><h1>${t(bi('Your software.<br>A real partner.','আপনার সফটওয়্যার।<br>সঙ্গে একজন সহযোগী।'))}</h1><p class="lead">${t(bi('Software development and ongoing care, led by Subroto Das.','সুব্রত দাসের নেতৃত্বে সফটওয়্যার ডেভেলপমেন্ট ও নিয়মিত সাপোর্ট।'))}</p><h2>${t(bi('Subroto Das','সুব্রত দাস'))}</h2><p class="founder-role">Founder & CEO</p><p>${t(bi('Full-stack, mobile and backend engineering. Explore the experience behind Subromart.','ফুলস্ট্যাক, মোবাইল ও ব্যাকএন্ড ইঞ্জিনিয়ারিং। Subromart-এর পেছনের অভিজ্ঞতা দেখুন।'))}</p><div class="button-row">${button(t(bi('Meet Subroto Das','সুব্রত দাসকে জানুন')),href('subroto-das',lang),'dark')}${button(t(bi('Explore our work','কাজ দেখুন')),href('work',lang),'text')}</div><a class="text-link about-systems" href="${profile.systems}" target="_blank" rel="noopener noreferrer">${t(bi('Systems Hub — my engineering notes','Systems Hub — আমার ইঞ্জিনিয়ারিং নোট'))}${icon('up')}</a></div><div class="founder-image"><img src="/assets/subroto-das.webp" alt="${t(bi('Subroto Das','সুব্রত দাস'))}" width="400" height="440"></div></section><section class="section container"><div class="promise-strip">${[bi('Clear scope','পরিষ্কার কাজের পরিধি'),bi('Reviewable progress','দৃশ্যমান অগ্রগতি'),bi('Support after launch','লঞ্চের পর সাপোর্ট')].map(v=>`<span>${icon('check')}${t(v)}</span>`).join('')}</div></section>${ctaBlock(lang)}`;}



const policyContent={
 privacy:[
  [bi('What this website stores','এই ওয়েবসাইট কী সংরক্ষণ করে'),bi('Your display mode, accent colour, reduced-motion preference, comparison selection and floating-button position may be saved in your browser’s local storage. These preferences stay on your device and can be reset through appearance settings or your browser settings.','আপনার ডিসপ্লে মোড, রং, অ্যানিমেশনের পছন্দ, তুলনার বাছাই ও ভাসমান বাটনের অবস্থান ব্রাউজারের লোকাল স্টোরেজে থাকতে পারে। এগুলো আপনার ডিভাইসেই থাকে। থিম সেটিংস বা ব্রাউজার সেটিংস থেকে মুছে দিতে পারবেন।')],
  [bi('Contact forms and project briefs','যোগাযোগের ফর্ম ও প্রজেক্ট ব্রিফ'),bi('The contact form prepares a message in your browser. It does not send your details to a Subromart server. When you choose WhatsApp or email, your chosen app opens with the information you entered. Review the message before sending it. Details sent to us may be used to discuss and respond to your enquiry.','যোগাযোগের ফর্ম আপনার ব্রাউজারেই বার্তা প্রস্তুত করে। তথ্য Subromart-এর সার্ভারে পাঠায় না। WhatsApp বা ইমেইল বেছে নিলে আপনার লেখা তথ্য নিয়ে সংশ্লিষ্ট অ্যাপ খুলবে। পাঠানোর আগে দেখে নিন। পাঠানো তথ্য আপনার প্রশ্নের উত্তর ও প্রজেক্ট আলোচনায় ব্যবহার করা হতে পারে।')],
  [bi('Third-party websites','তৃতীয় পক্ষের ওয়েবসাইট'),bi('Links to WhatsApp, social profiles, the founder’s portfolio and Systems Hub open external services. Their own privacy practices apply when you visit them. Fonts and visual assets on this website are served locally. This version does not include advertising trackers or third-party analytics scripts.','WhatsApp, সামাজিক প্রোফাইল, প্রতিষ্ঠাতার পোর্টফোলিও ও Systems Hub বাইরের সেবা। সেখানে গেলে তাদের নিজস্ব গোপনীয়তার নিয়ম প্রযোজ্য। এই সাইটের ফন্ট ও ভিজ্যুয়াল নিজস্ব ফাইল থেকে আসে। এই সংস্করণে বিজ্ঞাপনের ট্র্যাকার বা তৃতীয় পক্ষের অ্যানালিটিক্স স্ক্রিপ্ট নেই।')],
  [bi('Hosting and requests','হোস্টিং ও রিকোয়েস্ট'),bi('When deployed, the hosting provider may process normal request information such as IP address, requested page and browser details for delivery and security. The retention and location of those logs depend on the selected hosting provider.','ডেপ্লয় করা হলে হোস্টিং সেবাদাতা সাইট পরিবেশন ও নিরাপত্তার জন্য IP, পেজের রিকোয়েস্ট ও ব্রাউজারের মতো সাধারণ তথ্য প্রক্রিয়া করতে পারে। লগ কোথায় ও কত দিন থাকবে তা নির্বাচিত হোস্টিং সেবাদাতার ওপর নির্ভর করবে।')],
  [bi('Questions about your information','আপনার তথ্য নিয়ে প্রশ্ন'),bi('For questions about information you have shared with Subromart, contact subrotodas1714037@gmail.com. Do not submit passwords, medical records, financial credentials or other sensitive records through project enquiry messages.','Subromart-এর সাথে শেয়ার করা তথ্য নিয়ে প্রশ্ন থাকলে subrotodas1714037@gmail.com-এ লিখুন। প্রজেক্টের বার্তায় পাসওয়ার্ড, চিকিৎসা রেকর্ড, আর্থিক পরিচয়পত্র বা অন্য সংবেদনশীল তথ্য পাঠাবেন না।')]
 ],
 terms:[
  [bi('About the information here','এখানকার তথ্য সম্পর্কে'),bi('This website presents Subromart’s software and development services. Product names and interface previews describe solution concepts and possible modules. Preview data is illustrative. Availability, deliverables and final features are established in a written proposal.','এই ওয়েবসাইটে Subromart-এর সফটওয়্যার ও ডেভেলপমেন্ট সেবা উপস্থাপন করা হয়েছে। প্রোডাক্টের নাম ও প্রিভিউ সম্ভাব্য সলিউশন এবং মডিউল দেখায়। প্রিভিউয়ের তথ্য নমুনা। প্রাপ্যতা, ডেলিভারেবল ও চূড়ান্ত ফিচার লিখিত প্রস্তাবে নির্ধারিত হবে।')],
  [bi('Proposals and agreements','প্রস্তাব ও চুক্তি'),bi('Contacting us or requesting a demo does not create a purchase or booking. Project scope, pricing, payment milestones, licensing, ownership and support responsibilities must be agreed separately in writing before work begins.','যোগাযোগ করা বা ডেমো চাওয়া কোনো ক্রয় বা বুকিং নিশ্চিত করে না। কাজ শুরুর আগে কাজের পরিধি, মূল্য, পেমেন্ট মাইলস্টোন, লাইসেন্স, মালিকানা ও সাপোর্টের দায়িত্ব আলাদাভাবে লিখিত সম্মতিতে নির্ধারণ করতে হবে।')],
  [bi('Portfolio attribution','পোর্টফোলিওর পরিচয়'),bi('The work section includes the founder’s professional experience and engineering walkthroughs. Named employers, platforms and third-party projects are not presented as Subromart customers or products for resale. Their names and marks belong to their respective owners.','কাজের সেকশনে প্রতিষ্ঠাতার পেশাগত অভিজ্ঞতা ও ইঞ্জিনিয়ারিং ব্যাখ্যা আছে। উল্লেখিত নিয়োগদাতা, প্ল্যাটফর্ম ও তৃতীয় পক্ষের প্রজেক্টকে Subromart-এর ক্লায়েন্ট বা পুনর্বিক্রির পণ্য হিসেবে দেখানো হয়নি। সংশ্লিষ্ট নাম ও চিহ্ন তাদের নিজ নিজ মালিকের।')],
  [bi('External services and outcomes','বাইরের সেবা ও ফলাফল'),bi('External links, app-store reviews, payment accounts, hosting and search-engine inclusion depend on their respective providers. Search rankings, commercial outcomes and third-party approvals are not guaranteed by this website.','বাইরের লিংক, অ্যাপ স্টোর রিভিউ, পেমেন্ট অ্যাকাউন্ট, হোস্টিং ও সার্চ ইঞ্জিনে অন্তর্ভুক্তি সংশ্লিষ্ট সেবাদাতার ওপর নির্ভর করে। সার্চ র‍্যাঙ্কিং, ব্যবসায়িক ফলাফল বা তৃতীয় পক্ষের অনুমোদনের নিশ্চয়তা এই সাইট দেয় না।')]
 ],
 accessibility:[
  [bi('Navigation and reading','নেভিগেশন ও পড়া'),bi('This site uses semantic headings, labelled controls, a skip-to-content link and visible keyboard focus. Most content and all page links work without JavaScript. Interactive tools use JavaScript for previews, search, comparison and message preparation.','এই সাইটে অর্থপূর্ণ শিরোনাম, লেবেলসহ কন্ট্রোল, মূল কন্টেন্টে যাওয়ার লিংক ও দৃশ্যমান কিবোর্ড ফোকাস আছে। বেশিরভাগ কন্টেন্ট ও সব পেজের লিংক JavaScript ছাড়াই কাজ করে। প্রিভিউ, সার্চ, তুলনা ও বার্তা প্রস্তুতির টুলে JavaScript লাগে।')],
  [bi('Your display preferences','আপনার ডিসপ্লে পছন্দ'),bi('Choose light, dark or device-auto display mode. Adjust the accent colour and reduce animation in appearance settings. Device reduced-motion settings are respected. Content supports browser zoom and layouts adapt to small screens.','থিম সেটিংসে লাইট, ডার্ক বা ডিভাইস অটো বেছে নিন। রং পরিবর্তন ও অ্যানিমেশন কমাতে পারবেন। ডিভাইসের reduced-motion পছন্দ মানা হয়। ব্রাউজার জুম করা যায় এবং ছোট স্ক্রিনেও লেআউট মানিয়ে নেয়।')],
  [bi('Keyboard controls','কিবোর্ডে ব্যবহার'),bi('Use Tab to move between controls and Enter or Space to activate buttons. Escape closes dialogs. The WhatsApp button can be repositioned with Shift plus the arrow keys when focused, or reset from appearance settings.','Tab দিয়ে কন্ট্রোল বদলান এবং Enter বা Space দিয়ে বাটন ব্যবহার করুন। Escape দিয়ে ডায়ালগ বন্ধ হবে। WhatsApp বাটনে ফোকাস করে Shift ও অ্যারো কী দিয়ে অবস্থান বদলাতে পারবেন; থিম সেটিংস থেকে রিসেটও করা যায়।')],
  [bi('Report a problem','সমস্যা জানান'),bi('If something makes the site difficult to use, email subrotodas1714037@gmail.com with the page address, the task you were trying to complete and your device or assistive technology. We welcome specific feedback and do not claim universal accessibility conformance.','সাইট ব্যবহারে সমস্যা হলে পেজের ঠিকানা, কী করতে চেয়েছিলেন ও ডিভাইস বা সহায়ক প্রযুক্তির তথ্য দিয়ে subrotodas1714037@gmail.com-এ লিখুন। নির্দিষ্ট মতামতকে স্বাগত জানাই; সব পরিস্থিতিতে অ্যাকসেসিবিলিটির নিশ্চয়তা দাবি করছি না।')]
 ]
};
export function policyPage(kind,lang){const t=v=>tr(v,lang);return `<div class="container prose-layout"><aside class="prose-toc"><strong>${t(bi('On this page','এই পেজে'))}</strong>${policyContent[kind].map(([h],i)=>`<a href="#section-${i}">${t(h)}</a>`).join('')}<a href="${href('contact',lang)}">${t(bi('Contact us','যোগাযোগ করুন'))} ↗</a></aside><article class="prose">${policyContent[kind].map(([h,p],i)=>`<section id="section-${i}"><h2>${t(h)}</h2><p>${t(p)}</p></section>`).join('')}</article></div>`;}
