import { bi } from './data/content.mjs';
import { profile, tr, href, icon, button, ctaBlock } from './ui.mjs';

export const agreementTopics = [
 [bi('Scope & total cost','কাজের পরিধি ও মোট খরচ'),bi('Included features, exclusions, milestones and third-party fees.','অন্তর্ভুক্ত ফিচার, বাদ থাকা কাজ, মাইলস্টোন ও বাইরের সেবার খরচ।'),bi('What will the first release include? List the price, payment milestones, hosting and recurring service costs. Agree how changes will be estimated before they are built.','প্রথম সংস্করণে কী থাকবে? মূল্য, পেমেন্টের ধাপ, হোস্টিং ও নিয়মিত সেবার খরচ লিখে নিন। বাড়তি কাজ শুরু হওয়ার আগে তার হিসাব কীভাবে হবে, ঠিক করুন।')],
 [bi('Progress you can review','দেখে নেওয়ার সুযোগ'),bi('An agreed demo and acceptance checklist for each milestone.','প্রতি ধাপে ডেমো ও কাজ যাচাইয়ের নির্ধারিত তালিকা।'),bi('Choose who reviews each milestone, the workflows to demonstrate and the checks needed for acceptance. Record feedback and resolve the agreed issues before signing off.','প্রতি ধাপের কাজ কে দেখবেন, কোন কাজগুলো ডেমোতে দেখাতে হবে ও গ্রহণের মানদণ্ড কী হবে—ঠিক করুন। মতামত লিখে রাখুন এবং সম্মত সমস্যাগুলো সমাধানের পর ধাপটি গ্রহণ করুন।')],
 [bi('Ownership & handover','মালিকানা ও হস্তান্তর'),bi('Know which accounts, licences, files and documentation you receive.','কোন অ্যাকাউন্ট, লাইসেন্স, ফাইল ও ডকুমেন্টেশন পাবেন, জানুন।'),bi('Document who owns the domain, hosting, application accounts and business data. Specify source-code rights, third-party licences, data export, training and the handover format in your proposal.','ডোমেইন, হোস্টিং, অ্যাপের অ্যাকাউন্ট ও ব্যবসার তথ্যের মালিক কে, লিখে নিন। সোর্স কোডের অধিকার, বাইরের লাইসেন্স, ডেটা এক্সপোর্ট, প্রশিক্ষণ ও হস্তান্তরের ধরন প্রস্তাবে নির্ধারণ করুন।')],
 [bi('Support after launch','লঞ্চের পরের সাপোর্ট'),bi('Agree contacts, coverage, response targets and ongoing costs.','যোগাযোগ, সাপোর্টের পরিধি, সাড়া দেওয়ার লক্ষ্য ও নিয়মিত খরচ ঠিক করুন।'),bi('Separate bug fixes from new features. Agree support hours, response targets, maintenance fees, backup responsibilities and how access is transferred if the engagement ends. Coverage follows the written plan.','বাগ ফিক্স ও নতুন ফিচার আলাদা করুন। সাপোর্টের সময়, সাড়া দেওয়ার লক্ষ্য, মেইনটেন্যান্সের খরচ, ব্যাকআপের দায়িত্ব ও কাজ শেষে অ্যাকসেস হস্তান্তরের পদ্ধতি ঠিক করুন। লিখিত প্ল্যান অনুযায়ী সাপোর্ট হবে।')]
];

export function trustStrip(lang) {
 const t=v=>tr(v,lang);
 return `<section class="container trust-strip" aria-labelledby="trust-strip-title"><div><p class="eyebrow">${t(bi('BEFORE YOU COMMIT','সিদ্ধান্ত নেওয়ার আগে'))}</p><h2 id="trust-strip-title">${t(bi('Clarity comes first.','আগেই পরিষ্কার করে নিন।'))}</h2><a class="text-link" href="${href('client-care',lang)}">${t(bi('Our client checklist','ক্লায়েন্টের চেকলিস্ট'))}${icon('arrow')}</a></div><ul>${[bi('Written scope & cost','লিখিত কাজ ও খরচ'),bi('Milestone demos','ধাপে ধাপে ডেমো'),bi('Handover & support plan','হস্তান্তর ও সাপোর্ট প্ল্যান')].map(item=>`<li>${icon('check')}<span>${t(item)}</span></li>`).join('')}</ul></section>`;
}

export function founderPage(lang) {
 const t=v=>tr(v,lang);
 const external=(label,url,ico='up')=>button(label,url,'secondary',ico,'target="_blank" rel="noopener noreferrer"');
 return `<section class="container founder-profile"><div class="founder-profile-copy"><p class="eyebrow">${t(bi('THE PERSON BEHIND SUBROMART','SUBROMART-এর পেছনের মানুষ'))}</p><h1>Subroto Das<span lang="bn">সুব্রত দাস</span></h1><p class="profile-role">${t(bi('Founder & CEO, Subromart','প্রতিষ্ঠাতা ও সিইও, Subromart'))}</p><p class="lead">${t(bi('Software engineer. Your direct point of contact.','সফটওয়্যার ইঞ্জিনিয়ার। সরাসরি যোগাযোগের মানুষ।'))}</p><p>${t(bi('Based in Dhaka, Bangladesh. I work across full-stack web applications, mobile apps and backend systems. At Subromart, we plan the build and the ongoing care together.','ঢাকা, বাংলাদেশ থেকে ফুলস্ট্যাক ওয়েব অ্যাপ্লিকেশন, মোবাইল অ্যাপ ও ব্যাকএন্ড সিস্টেম নিয়ে কাজ করি। Subromart-এ সফটওয়্যার তৈরি ও নিয়মিত যত্নের পরিকল্পনা একসঙ্গে করি।'))}</p><div class="button-row">${button(t(bi('Discuss your project','প্রজেক্ট নিয়ে কথা বলুন')),href('contact',lang),'dark')}${external(t(bi('Professional portfolio','পেশাগত পোর্টফোলিও')),profile.website)}</div></div><figure class="profile-portrait"><img src="/assets/subroto-das.webp" width="640" height="747" alt="Subroto Das — ${t(bi('founder of Subromart','Subromart-এর প্রতিষ্ঠাতা'))}"><figcaption>${icon('pin')}${t(bi(profile.location,profile.locationBn))}</figcaption></figure></section>
 <section class="container section profile-evidence"><div><p class="eyebrow">${t(bi('EXPLORE THE WORK','কাজগুলো দেখে নিন'))}</p><h2>${t(bi('A profile you can follow.','পরিচয় ও কাজ, একসঙ্গে।'))}</h2><p>${t(bi('See the original portfolio, public code and engineering notes. Professional experience is attributed separately from Subromart projects.','মূল পোর্টফোলিও, প্রকাশ্য কোড ও ইঞ্জিনিয়ারিং নোট দেখুন। পেশাগত অভিজ্ঞতা ও Subromart-এর প্রজেক্টের পরিচয় আলাদাভাবে দেওয়া আছে।'))}</p><a class="text-link" href="${href('work',lang)}">${t(bi('Explore professional work','পেশাগত কাজ দেখুন'))}${icon('arrow')}</a></div><nav class="profile-links" aria-label="${t(bi('Subroto Das profiles and work','সুব্রত দাসের প্রোফাইল ও কাজ'))}">${[[profile.social.linkedin,'LinkedIn',bi('Professional background','পেশাগত পরিচয়')],[profile.social.github,'GitHub',bi('Public code & repositories','প্রকাশ্য কোড ও রিপোজিটরি')],[profile.systems,'Systems Hub',bi('Engineering notes & walkthroughs','ইঞ্জিনিয়ারিং নোট ও ব্যাখ্যা')],[profile.social.youtube,'bugCoder Academy',bi('Programming videos','প্রোগ্রামিংয়ের ভিডিও')]].map(([url,name,detail])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><span><strong>${name}</strong><small>${t(detail)}</small></span>${icon('up')}</a>`).join('')}</nav></section>
 <section class="container section profile-expertise"><h2>${t(bi('What we can build together','একসঙ্গে যা তৈরি করতে পারি'))}</h2><div class="related-links">${[['services/custom-software',bi('Business software & digital products','বিজনেস সফটওয়্যার ও ডিজিটাল প্রোডাক্ট')],['solutions/ecommerce',bi('E-commerce websites','ই-কমার্স ওয়েবসাইট')],['services/mobile-apps',bi('Android & iOS apps','Android ও iOS অ্যাপ')],['services/maintenance',bi('Software maintenance','সফটওয়্যার মেইনটেন্যান্স')]].map(([slug,label])=>`<a href="${href(slug,lang)}">${t(label)}${icon('arrow')}</a>`).join('')}</div><a class="text-link profile-care-link" href="${href('client-care',lang)}">${t(bi('What to agree before we start','শুরুর আগে যা ঠিক করে নেবেন'))}${icon('arrow')}</a></section>${ctaBlock(lang)}`;
}

export function clientCarePage(lang) {
 const t=v=>tr(v,lang);
 return `<section class="container page-intro"><p class="eyebrow">${t(bi('WORK WITH CONFIDENCE','জেনে বুঝে শুরু করুন'))}</p><h1>${t(bi('Know what you’re getting.','কী পাচ্ছেন, আগে জানুন।'))}</h1><p>${t(bi('Four conversations before a project begins. Each one belongs in your written proposal.','প্রজেক্টের আগে চারটি বিষয় ঠিক করুন। প্রতিটি আপনার লিখিত প্রস্তাবে থাকবে।'))}</p><div class="button-row">${button(t(bi('Download the checklist','চেকলিস্ট ডাউনলোড')),`/assets/downloads/project-checklist-${lang}.txt`,'dark','download','download')}${button(t(bi('Meet Subroto Das','সুব্রত দাসকে জানুন')),href('subroto-das',lang),'text')}</div></section>
 <section class="container section agreement-section" aria-label="${t(bi('Project agreement checklist','প্রজেক্টের সম্মতির চেকলিস্ট'))}"><div class="agreement-grid">${agreementTopics.map(([title,summary,detail],i)=>`<article class="agreement-card"><span class="agreement-number">0${i+1}</span><h2>${t(title)}</h2><p>${t(summary)}</p><details><summary>${t(bi('What to confirm','যা নিশ্চিত করবেন'))}${icon('plus')}</summary><p>${t(detail)}</p></details></article>`).join('')}</div><p class="section-note">${t(bi('Use this as a discussion checklist. The agreed proposal defines your deliverables, rights and support.','আলোচনার জন্য এই চেকলিস্ট ব্যবহার করুন। সম্মত প্রস্তাবেই আপনার ডেলিভারেবল, অধিকার ও সাপোর্ট নির্ধারিত হবে।'))}</p></section>
 <section class="container section evidence-bar"><div><p class="eyebrow">${t(bi('MAKE AN INFORMED CHOICE','দেখে বুঝে সিদ্ধান্ত নিন'))}</p><h2>${t(bi('See the people. Explore the product.','পরিচয় জানুন। প্রোডাক্ট দেখুন।'))}</h2></div><div class="evidence-actions">${button(t(bi('Founder & public profiles','প্রতিষ্ঠাতা ও প্রোফাইল')),href('subroto-das',lang),'secondary')}${button(t(bi('Request a guided demo','গাইডেড ডেমো চাই')),href('book-demo',lang),'secondary')}</div></section>${ctaBlock(lang)}`;
}

export function projectChecklist(lang) {
 const t=v=>tr(v,lang);
 return `${t(bi('SUBROMART — PROJECT AGREEMENT CHECKLIST','SUBROMART — প্রজেক্টের সম্মতির চেকলিস্ট'))}\nhttps://subromart.com${href('client-care',lang)}\n\n${t(bi('Project name:','প্রজেক্টের নাম:'))} ____________________\n${t(bi('Contact person:','যোগাযোগের ব্যক্তি:'))} ____________________\n\n${agreementTopics.map(([title,,detail])=>`[ ] ${t(title)}\n${t(detail)}\n${t(bi('Agreed notes:','সম্মত বিষয়:'))} ____________________`).join('\n\n')}\n\n${t(bi('For discussion; this checklist is not a signed proposal or purchase. Do not include passwords or private customer records.','আলোচনার জন্য; এই চেকলিস্ট স্বাক্ষরিত প্রস্তাব বা ক্রয় নয়। পাসওয়ার্ড বা গ্রাহকের ব্যক্তিগত রেকর্ড লিখবেন না।'))}\n\nSubroto Das | Subromart\n${profile.email}\n${profile.website}\n`;
}
